export enum Colors {
  Black = "black",
  White = "white",
  GreyLiver = "grey-liver",
  GreyDark = "grey-dark",
  Purple = "purple",
  Green = "green",
  GreenLight = "green-light",
  Orange = "orange",
  OrangeLight = "range-light",
  Grey = "grey",
  GreyLight = "grey-light",
  GreyBlue = "grey-blue",
  GreyDim = "grey-dim",
  Red = "red",
}
